### ISSUE TITLE
Citation 

### ISSUE THREAD

**Issue by nequalstim** [lukexyz/CV-Instagram-Filters#1]
Hey, 

this repo looks very much similar to a blog post by Michele Pratusevich. 
https://www.practicepython.org/blog/2016/12/20/instagram-filters-python.html

Would be great if you cited her work, if yours is based on this.

**Comment by lukexyz** [comment]
You're right - I learned about this from an old PyCon talk. Thanks for the link I've added it to the readme. b0c57ff
